# Generated by Django 4.1.2 on 2022-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_control", "0003_useractivities"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="shop_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
