version: '3'
services:
  inventory_api:
    container_name: inventory_api
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/inventory_api
    volumes:
      - inventory_api:/data/inventory_api
    restart: always

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: inventory_backend
    restart: always
    volumes: 
      - .:/inventory_backend
    ports:
      - "8000:8000"
    depends_on:
      - inventory_api

  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "5050:80"


volumes:
  inventory_api: