# Generated by Django 4.1.2 on 2022-12-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_control", "0003_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorygroup",
            name="belongs_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups_relations",
                to="app_control.inventorygroup",
            ),
        ),
    ]
